// Seed de perfiles de industria para CosteAR.
// Migra los 11 perfiles hardcodeados de industry-profile.ts a la tabla industry_profiles.
// Uso: tsx --env-file=.env prisma/seed-industry-profiles.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const profiles = [
  {
    category: 'AGRO',
    label: 'Agropecuario',
    mpKeywords: [
      'semilla', 'simiente', 'agroquímico', 'agroquimico', 'herbicida', 'fungicida',
      'insecticida', 'fertilizante', 'abono', 'inoculante', 'fosfato',
      'forraje', 'alimento balanceado', 'pellet', 'silo',
      'bolsa', 'bolsón', 'arpillera', 'envase agrícola',
      'riego', 'goteo', 'aspersor',
      'soja', 'maíz', 'trigo', 'girasol', 'sorgo', 'algodón',
      'vid', 'uva', 'mosto', 'sulfato de cobre',
    ],
    cipKeywords: [
      'alquiler campo', 'arrendamiento', 'flete', 'transporte grano',
      'seguro agrícola', 'seguro granizo', 'seguro climático',
      'servicio de cosecha', 'contratista cosecha', 'trilla',
      'pulverización aérea', 'siembra directa servicio',
      'honorarios agrónomo', 'análisis suelo',
      'mantenimiento maquinaria', 'reparacion tractor', 'repuesto agrícola',
      'telefonía rural', 'internet rural', 'electricidad rural',
      'gasoil', 'combustible', 'nafta', 'lubricante',
      'veterinaria', 'veterinario', 'producto veterinario', 'medicamento veterinario',
      'honorarios veterinario', 'vacuna', 'vacunación', 'vacunacion',
      'antiparasitario', 'medicamento animal', 'sanidad animal', 'desparasitación',
      'desparasitacion',
    ],
    modKeywords: [
      'jornada', 'peón rural', 'cosechador', 'tractorista',
      'mano de obra rural', 'contratación temporaria',
      'personal de campo', 'capataz',
    ],
    eventKeywords: [
      'sequía', 'sequia', 'lluvia', 'granizo', 'helada', 'tormenta',
      'inundación', 'inundacion', 'viento zonda', 'sudestada',
      'plaga', 'langosta', 'chinche', 'roya',
      'siembra tardía', 'no se pudo cosechar', 'pérdida de cosecha',
      'cosecha frustrada', 'no hubo producción', 'campo anegado',
    ],
    lossKeywords: [
      'pérdida de grano', 'merma', 'siniestro', 'daño climático',
      'grano húmedo', 'grano brotado', 'aflatoxina',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'AVICULTURA',
    label: 'Avicultura de postura',
    mpKeywords: [
      'balanceado', 'alimento balanceado', 'alimento para ponedora',
      'maíz', 'maiz', 'sorgo', 'soja', 'expeller',
      'harina de soja', 'poroto de soja', 'afrechillo', 'salvado de trigo',
      'aceite vegetal', 'grasa vegetal',
      'núcleo vitamínico', 'nucleo vitaminico', 'núcleo mineral', 'nucleo mineral',
      'premezcla', 'corrector vitamínico', 'corrector vitaminico',
      'metionina', 'lisina', 'aminoácido', 'aminoacido',
      'carbonato de calcio', 'conchilla', 'cáscara de ostra', 'cascara de ostra',
      'fosfato bicálcico', 'fosfato bicalcico', 'calcáreo', 'calcareo',
      'maple', 'maples', 'huevera', 'estuche para huevo', 'caja para huevos',
    ],
    cipKeywords: [
      'energía eléctrica', 'energia electrica', 'electricidad',
      'luz eléctrica', 'luz electrica', 'kwh',
      'suministro eléctrico', 'suministro electrico',
      'grupo electrógeno', 'grupo electrogeno',
      'generador eléctrico', 'generador electrico',
      'calefacción', 'calefaccion', 'calefactor', 'campana calefactora',
      'ventilación', 'ventilacion', 'extractor', 'panel de enfriamiento',
      'gas envasado', 'garrafa', 'gas natural',
      'vacuna', 'vacunación', 'vacunacion', 'antibiótico', 'antibiotico',
      'antiparasitario', 'coccidiostato', 'desinfectante',
      'desinfección', 'desinfeccion', 'sanidad', 'bioseguridad',
      'producto veterinario', 'medicamento veterinario',
      'honorarios veterinario', 'honorarios veterinaria',
      'análisis de laboratorio', 'analisis de laboratorio', 'necropsia',
      'control de plagas', 'desratización', 'desratizacion',
      'fumigación', 'fumigacion',
      'mantenimiento de galpones', 'mantenimiento de galpón', 'mantenimiento de galpon',
      'reparación de galpón', 'reparacion de galpon',
      'comedero', 'bebedero', 'jaula', 'nidal',
      'cinta de recolección', 'cinta de recoleccion',
      'chapa de techo', 'chapas de techo',
      'cama de galpón', 'cama de galpon', 'viruta', 'cascarilla de arroz',
      'agua de bebida', 'perforación', 'perforacion', 'bomba de agua',
      'amortización del plantel', 'amortizacion del plantel',
      'amortización de gallinas', 'amortizacion de gallinas',
      'alquiler de campo', 'arrendamiento', 'seguro del establecimiento',
      'telefonía rural', 'telefonia rural', 'internet rural',
    ],
    modKeywords: [
      'operario de galpón', 'operario de galpon',
      'operarios de galpón', 'operarios de galpon',
      'personal de galpón', 'personal de galpon', 'galponero', 'galponeros',
      'peón de galpón', 'peon de galpon',
      'recolector de huevo', 'recolección de huevo', 'recoleccion de huevo',
      'clasificador de huevo', 'clasificación de huevo', 'clasificacion de huevo',
      'envasador de huevo', 'jornal de galpón', 'jornal de galpon',
      'mano de obra de galpón', 'mano de obra de galpon',
    ],
    eventKeywords: [
      'brote de newcastle', 'brote de influenza aviar', 'gripe aviar',
      'brote sanitario', 'cuarentena sanitaria', 'despoblamiento',
      'clausura sanitaria', 'senasa clausuró', 'senasa clausuro',
      'ola de calor', 'golpe de calor', 'estrés térmico', 'estres termico',
      'corte de luz', 'corte de energía', 'corte de energia',
      'se cortó la luz', 'se corto la luz',
      'falló el grupo electrógeno', 'fallo el grupo electrogeno',
      'se quedaron sin agua',
      'caída de postura', 'caida de postura', 'bajó la postura', 'bajo la postura',
    ],
    lossKeywords: [
      'mortandad', 'mortalidad del plantel', 'gallinas muertas', 'gallina muerta',
      'huevo roto', 'huevos rotos', 'huevo quebrado', 'huevos quebrados',
      'huevo fisurado', 'huevos fisurados', 'huevo sucio', 'huevos sucios',
      'huevo descartado', 'huevos descartados', 'merma de postura',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: 'cajon',
    isActive: true,
  },
  {
    category: 'GASTRONOMIA',
    label: 'Gastronomía / Alimentos',
    mpKeywords: [
      'carne', 'pollo', 'cerdo', 'pescado', 'mariscos', 'vacuno', 'cordero',
      'leche', 'queso', 'manteca', 'crema', 'yogur', 'mantequilla',
      'verdura', 'fruta', 'legumbre', 'papa', 'tomate', 'cebolla', 'lechuga',
      'harina', 'azúcar', 'azucar', 'arroz', 'fideos', 'pasta', 'sémola',
      'levadura', 'sal', 'aceite', 'vinagre',
      'vino', 'cerveza', 'gaseosa', 'agua mineral', 'jugo', 'bebida',
      'descartable', 'vaso descartable', 'plato descartable', 'envase', 'film',
      'gas envasado', 'garrafa', 'gas cocina',
      'condimento', 'especias', 'salsa', 'aderezo',
    ],
    cipKeywords: [
      'alquiler local', 'alquiler salón', 'expensas',
      'seguro', 'alarma', 'seguridad',
      'limpieza', 'desinfección', 'desinfeccion', 'fumigación',
      'bromatología', 'habilitación municipal',
      'electricidad', 'luz', 'agua potable',
      'internet', 'teléfono', 'telefono',
      'vajilla', 'menaje', 'cubertería', 'silla', 'mesa',
      'mantenimiento', 'reparación heladera', 'reparación horno',
    ],
    modKeywords: [
      'sueldo cocinero', 'sueldo mozo', 'sueldo personal',
      'liquidación', 'honorarios', 'personal gastronómico',
    ],
    eventKeywords: [
      'clausura', 'clausuraron', 'habilitación vencida', 'bromatología',
      'inspección', 'multa municipal', 'cierre temporario',
      'robo', 'hurto', 'entrada forzada',
      'incendio cocina', 'accidente cocina',
      'falta de luz', 'corte de gas',
    ],
    lossKeywords: [
      'se quemó', 'quemé', 'se perdió', 'se echó a perder', 'se venció',
      'merma', 'desperdicio', 'vencimiento', 'se pudrió',
      'rotura heladera', 'corte de frío',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'MANUFACTURA',
    label: 'Manufactura / Industria',
    mpKeywords: [
      'materia prima', 'insumo', 'material productivo',
      'chapa', 'alambre', 'hierro', 'acero', 'aluminio', 'cobre',
      'plástico', 'resina', 'polietileno', 'polipropileno', 'PVC',
      'tela', 'hilo', 'tinta', 'pintura industrial',
      'madera', 'tablero', 'MDF', 'aglomerado',
      'vidrio', 'cerámica', 'porcelana',
      'papel', 'cartón', 'bobina', 'rollo',
      'solvente', 'diluyente', 'adhesivo', 'pegamento',
      'químico', 'producto químico', 'reactivo',
      'envase', 'embalaje', 'packaging',
      'componente', 'pieza', 'parte', 'repuesto producción',
    ],
    cipKeywords: [
      'alquiler planta', 'alquiler galpón', 'alquiler nave industrial',
      'seguro planta', 'seguro maquinaria',
      'mantenimiento máquinas', 'mantenimiento equipos',
      'energía eléctrica', 'electricidad', 'luz eléctrica',
      'gas natural', 'vapor',
      'agua industrial', 'tratamiento efluentes',
      'transporte', 'flete', 'logística',
      'depreciación', 'amortización',
      'limpieza industrial', 'residuos',
    ],
    modKeywords: [
      'operario', 'operarios', 'línea de producción', 'personal producción',
      'horas extra', 'turno', 'jornada producción',
    ],
    eventKeywords: [
      'paró la máquina', 'falla de equipos', 'avería',
      'corte de luz', 'corte de gas', 'paró la planta',
      'paro sindical', 'huelga', 'lock-out',
      'incendio planta', 'explosión',
    ],
    lossKeywords: [
      'producto defectuoso', 'rechazo calidad', 'scrap', 'desperdicio',
      'merma de proceso', 'rotura en proceso',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'CONSTRUCCION',
    label: 'Construcción / Obras',
    mpKeywords: [
      'cemento', 'hormigón', 'hormigon', 'arena', 'canto rodado', 'cascajo',
      'hierro', 'varilla', 'malla', 'alambre para construcción',
      'ladrillo', 'bloque', 'adoquín', 'loseta', 'baldosa', 'cerámica',
      'madera obra', 'tirante', 'viga', 'encofrado',
      'pintura', 'látex', 'esmalte', 'impermeabilizante',
      'cañería', 'caño', 'fitting', 'válvula',
      'cable eléctrico', 'tablero', 'disyuntor',
      'yeso', 'revoque', 'membrana', 'aislante',
      'vidrio', 'ventana', 'puerta', 'marco',
    ],
    cipKeywords: [
      'alquiler andamio', 'alquiler retroexcavadora', 'alquiler hormigonera',
      'alquiler equipo', 'alquiler maquinaria vial',
      'seguro obra', 'ART construcción',
      'transporte material', 'flete materiales',
      'honorarios arquitecto', 'honorarios ingeniero',
      'permiso de obra', 'visado plano', 'habilitación obra',
      'electricidad provisional obra',
    ],
    modKeywords: [
      'albañil', 'plomero', 'electricista', 'carpintero',
      'mano de obra obra', 'jornal', 'destajero',
      'subcontratista', 'cuadrilla',
    ],
    eventKeywords: [
      'lluvia paró obra', 'suspensión por lluvia', 'día de lluvia',
      'accidente obra', 'herido en obra',
      'vecino denunció', 'municipio paró obra',
    ],
    lossKeywords: [
      'material robado', 'material húmedo', 'cemento fraguado',
      'desperdicio material',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'TEXTIL',
    label: 'Textil / Indumentaria',
    mpKeywords: [
      'tela', 'género', 'tejido', 'tul', 'encaje', 'raso',
      'hilo', 'hilo de coser', 'hilo bordado',
      'botón', 'cierre', 'hebilla', 'broche', 'velcro', 'elástico',
      'tinte', 'tintura', 'colorante textil',
      'entretela', 'forro', 'relleno', 'guata',
      'etiqueta', 'hangtag', 'bolsa poly',
      'cinta métrica', 'patrón', 'molde',
    ],
    cipKeywords: [
      'alquiler taller', 'alquiler local',
      'mantenimiento máquina de coser', 'servicio máquina',
      'electricidad taller', 'luz taller',
      'transporte colecciones', 'flete mercadería',
      'seguro taller',
    ],
    modKeywords: [
      'costurera', 'costureras', 'bordadora', 'tejedor',
      'personal confección', 'producción por pieza', 'destajo',
    ],
    eventKeywords: [
      'corte de luz paró la producción',
      'máquina rota', 'avería máquina de coser',
    ],
    lossKeywords: [
      'tela manchada', 'defecto tela', 'corte mal hecho',
      'merma tela',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'SALUD',
    label: 'Salud / Farmacia',
    mpKeywords: [
      'medicamento', 'droga', 'fármaco', 'farmaco', 'principio activo',
      'insumo médico', 'material descartable médico',
      'jeringa', 'guante', 'gasa', 'vendaje', 'catéter',
      'reactivo laboratorio', 'kit diagnóstico', 'tira reactiva',
      'vacuna', 'suero', 'solución fisiológica', 'glucosa',
      'rayos X', 'film radiológico', 'contraste',
      'prótesis', 'implante', 'material quirúrgico',
    ],
    cipKeywords: [
      'alquiler consultorio', 'alquiler clínica',
      'mantenimiento equipo médico', 'calibración',
      'habilitación sanitaria', 'ANMAT', 'ministerio salud',
      'seguro mala praxis', 'seguro médico',
      'electricidad clínica', 'gas clínica',
    ],
    modKeywords: [
      'sueldo médico', 'sueldo enfermero', 'honorario médico',
      'guardia', 'turno médico',
    ],
    eventKeywords: [
      'habilitación vencida', 'inspección ANMAT', 'alerta sanitaria',
      'corte de frío vacunas', 'falla cadena de frío',
    ],
    lossKeywords: [
      'medicamento vencido', 'vacuna inutilizada',
      'insumo en mal estado',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'SERVICIOS',
    label: 'Servicios Profesionales / IT',
    mpKeywords: [
      'licencia software', 'suscripción cloud', 'API', 'hosting',
      'dominio', 'SSL', 'servidor',
      'papel', 'tóner', 'cartucho', 'resma',
    ],
    cipKeywords: [
      'alquiler oficina', 'coworking',
      'internet', 'telefonía', 'celular',
      'software administrativo', 'CRM', 'ERP',
      'seguro responsabilidad civil', 'seguro contenido',
      'electricidad oficina', 'agua',
      'limpieza oficina', 'seguridad',
    ],
    modKeywords: [
      'honorario', 'consultoría', 'sueldo profesional',
      'horas de servicio', 'factura honorarios',
    ],
    eventKeywords: [
      'corte de internet', 'caída del servidor', 'hack', 'ataque informático',
      'incendio oficina', 'robo equipos',
    ],
    lossKeywords: [
      'pérdida de datos', 'equipo robado', 'laptop robada',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'COMERCIO',
    label: 'Comercio / Distribución',
    mpKeywords: [
      'mercadería', 'stock', 'producto para reventa',
      'compra de mercadería', 'reposición stock',
    ],
    cipKeywords: [
      'alquiler local', 'alquiler depósito',
      'flete', 'transporte mercadería', 'logística',
      'seguro mercadería', 'seguro local',
      'electricidad local', 'gas local',
      'cámara de seguridad', 'alarma',
    ],
    modKeywords: [
      'sueldo vendedor', 'comisión ventas', 'personal local',
    ],
    eventKeywords: [
      'robo', 'hurto', 'asalto', 'entradera',
      'clausura comercial', 'habilitación vencida',
      'desabastecimiento', 'quiebre de stock',
    ],
    lossKeywords: [
      'mercadería robada', 'stock faltante', 'rotura mercadería',
      'mercadería vencida', 'producto vencido',
    ],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'TRANSPORTE',
    label: 'Transporte / Logística',
    mpKeywords: [
      'gasoil', 'combustible', 'nafta', 'GNC', 'gas natural comprimido',
      'lubricante', 'aceite motor', 'neumático', 'goma', 'cubiertas',
      'repuesto', 'filtro', 'pastillas freno', 'batería',
      'peaje', 'rodado',
    ],
    cipKeywords: [
      'seguro automotor', 'seguro flota', 'VTV', 'revisión técnica',
      'patente', 'registro', 'habilitación transporte',
      'alquiler cochera', 'garaje',
      'rastreo GPS', 'monitoreo flota',
      'energía eléctrica', 'energia electrica', 'electricidad', 'luz del depósito',
      'gas natural',
    ],
    modKeywords: [
      'sueldo chofer', 'viático', 'horas chofer',
    ],
    eventKeywords: [
      'accidente vial', 'choque', 'siniestro vehicular',
      'ruta cortada', 'piquete', 'corte de ruta',
    ],
    lossKeywords: [
      'carga robada', 'carga dañada', 'derrame',
    ],
    energyIsMP: false,
    fuelIsMP: true,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
  {
    category: 'DEFAULT',
    label: 'Genérico',
    mpKeywords: [
      'materia prima', 'insumo', 'material', ' kg', 'litro', 'tonelada',
      'bobina', 'rollo', 'envase', 'embalaje', 'chapa', 'alambre',
      'tela', 'hilo', 'resina', 'pintura', 'solvente', 'madera',
      'cartón', 'plástico',
    ],
    cipKeywords: [
      'alquiler', 'alq.', 'servicio', 'energía', 'energia', 'electricidad',
      'gas', 'mantenimiento', 'mant.', 'seguro', 'limpieza', 'vigilancia',
      'telefonía', 'telefonia', 'internet', 'agua', 'abono', 'cuota',
    ],
    modKeywords: [],
    eventKeywords: [],
    lossKeywords: [],
    energyIsMP: false,
    fuelIsMP: false,
    detectPatterns: [],
    measurementUnit: null,
    isActive: true,
  },
];

async function main() {
  console.log('Seeding industry profiles…');

  for (const profile of profiles) {
    await prisma.industryProfile.upsert({
      where: { category: profile.category },
      update: profile,
      create: profile,
    });
    console.log(`  ✓ ${profile.category}`);
  }

  console.log(`Done. ${profiles.length} profiles upserted.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
